### ISSUE TITLE
document prerequisites

### ISSUE THREAD

**Issue by khimaros** [egormanga/pinephone-fingerprint#1]
from what i've been able to gather so far:

python dependencies:

```
# apt install -y python3-crccheck python3-periphery
```

load the `i2c-dev` kernel module:

```
# modprobe i2c-dev
```

troubleshooting tools:

```
# apt install -y i2c-tools
# i2cdetect -l
# i2cdetect -F 2
```

**Comment by egormanga** [comment]
Sure, there will be a proper `README` and `requirements.txt` as soon as the code will be ready for testing.
